### PR TITLE
Update 1.AboutME

### PR DESCRIPTION
**Pull request by tejan-singh**
add tejan-singh.md in 1.AboutME folder.

### CODE REVIEW

**Comment by SpooderManEXE** [comment]
please use the template provided

**Comment by SpooderManEXE** [comment]
i think you missed "---"

**Comment by SpooderManEXE** [comment]
i have updated it for you

**Comment by tejan-singh** [comment]
Thanks for your help. Will this count for the hacktoberfest 2020? I am not able to see update on my hactoberfest profile.

**Comment by SpooderManEXE** [comment]
Only PRs made during the month of October will count.

**Pull request merged**
